version: '3'
services:
  myapp:
    image: your_image_name:tag
    ports:
      - 8080:80
    volumes:
      - ./data:/app/data
    environment:
      - DB_HOST=your_db_host
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
